# netlify.toml

[build]
  base = "/build/"
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION = "14" }
  functions = "./functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 